### ISSUE TITLE
Outdated library version.

### ISSUE THREAD

**Issue by laggycomputer** [yikersdev/Assistance#2]
I'd like to point out that a new version of `discord.py` was released recently. Many breaking changes were introduced. See the migrating guide at https://discordpy.readthedocs.io/en/latest/migrating.html.

**Comment by blomer** [comment]
I am only going to respond to this issue for now.

I do not actively develop anything. I don't understand why people think that I am dedicating everything to this project. I have a life like everyone else here, and I am receiving nothing for this project. If you would like to work on it and fix the issues yourself, then please fork this and make it better. I am in no way a professional, I just program as a hobby. I barely ever have time for myself anymore nor do I have time to develop a free project, sorry.

**Comment by laggycomputer** [comment]
I'm sorry that I provoked such a bad attitude from you. If you have no share in the project presently, I personally do not think that bitterly denying efforts to improve an open source project is the way out. If you `barely ever have time`, why are you bitterly rejecting valid pointers about project problems? If you `just program as a hobby`, why don't you either archive or continue working on the project? I did not make any indication of `think[ing] that I am dedicating everything to this project` or that you do not `have a life like everyone else here`. Please calm down.

**Comment by laggycomputer** [comment]
If you really insist...

**Comment by blomer** [comment]
I never said I wouldnt look this over when I get time, I just don't have time at the moment with school and work.

**Comment by TheRockettek** [comment]
You ok laggy?
